### ISSUE TITLE
18_backgrounding_processes/server.c has door routines from next step

### ISSUE THREAD

**Issue by JRWynneIII** [robertdfrench/revolving-door#13]
Looks like in server.c for step 1.8 (18?) has the server.c from step 2 (20?). This preemptively introduces some door specific code before explaining it. That step effectively introduces 2 new topics, of which only 1 is explained. Just a minor detail, and probably not an issue. Just something i noticed!

This tutorial is fantastic btw :+1:

**Comment by robertdfrench** [comment]
Good catch! That material definitely does not belong in 18 (It's hex, so that the Makefile can automatically arrange Prev / Next links between adjacent lessons).
