### ISSUE TITLE
Finish OpenIndiana Setup Guide

### ISSUE THREAD

**Issue by robertdfrench** [robertdfrench/revolving-door#4]

**Comment by AnthonyDiGirolamo** [comment]
+1 Copy/pasteable lines for adding a user and setting up openssh would be nice.

**Comment by robertdfrench** [comment]
@AnthonyDiGirolamo see what you think of it now. There isn't much that can be copy+pasted, so I took screenshots wherever possible.

**Comment by robertdfrench** [comment]
@AnthonyDiGirolamo I'm closing this because @jack-morrison went through it and suggested another fix (#14 / #15). Either of y'all feel free to reopen if something still feels missing. Thank you both for your help.
